# Gradle
# Build your Java project and run tests with Gradle.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

parameters:
  continueOnError: false
  publishTestResults: false

steps:
  - task: CacheBeta@0
    inputs:
      key: |
        gradle
        $(Agent.JobName)
      path: $(GRADLE_USER_HOME)
    displayName: Gradle build cache

  - bash: |
      set -e
      # when executing on an Azure Pipelines build agent (not in a container)
      # default to java 11
      if [ -n "${JAVA_HOME_11_X64}" ]; then
        export JAVA_HOME="${JAVA_HOME_11_X64}"
      fi
      ./gradlew --version
      ./gradlew --build-cache --scan --warning-mode=all -Dplatform.tooling.support.tests.enabled=true build
      # stop the gradle daemon so there isn't a problem with reading files in the SaveCache step
      ./gradlew --stop
    env:
      LC_ALL: en_US.UTF-8
    displayName: Test
    continueOnError: ${{ parameters.continueOnError }}

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFiles: '*/build/test-results/test/TEST-*.xml'
    condition: eq(${{ parameters.publishTestResults }}, true)
